// session actions
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

// listener actions
export const FIREBASE_LISTEN_REQUESTED = 'FIREBASE_LISTEN_REQUESTED';
export const FIREBASE_LISTEN_FULFILLED = 'FIREBASE_LISTEN_FULFILLED'
export const FIREBASE_LISTEN_REJECTED = 'FIREBASE_LISTEN_REJECTED';
export const FIREBASE_LISTEN_REMOVED = 'FIREBASE_LISTEN_REMOVED';
export const FIREBASE_LISTEN_CHILD_ADDED = 'FIREBASE_LISTEN_CHILD_ADDED';
export const FIREBASE_LISTEN_CHILD_REMOVED = 'FIREBASE_LISTEN_CHILD_REMOVED';
export const FIREBASE_LISTEN_CHILD_CHANGED = 'FIREBASE_LISTEN_CHILD_CHANGED';

// user actions
export const RECEIVE_USER = 'RECEIVE_USER';

// post actions
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
